import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "welcometo": "Welcome To",
          "takecareofyourhealth": "Take Care Of Your Health",
          "manageYourHealth": 'Manage your health with us',
          "with": "With",
          'goodmorning': "Good Morning",
          'goodEvening': 'Good Evening',
          'goodNight': 'Good Night',
          'goodAfterNoon': 'Good Afternoon',
          'onlineOffline': 'Online & Offline ',
          'consultations': 'Consultations',
          'booknow': 'Book Now',
          'selectservices': 'Select Services',
          'homeSample': 'Home Sample',
          'imageBooking': 'Image Booking',
          'doctorConsultation': 'Doctor Consultation',
          'reports': 'Reports',
          'healthSummary': 'Health Summary',
          'healthAnalysis': 'Health Analysis',
          'todayAvailable': 'Today Available',
          'generalConsultation': 'General Consultation',
          'getAppointment': 'Get Appointment',
          'home': 'Home',
          'profile': 'Profile',
          'schedule': 'Schedule',
          'help': 'Help',
          'history': 'History',
          'familyMembers': 'Family Members',
          'location': 'Location',
          'wallet': 'Wallet',
          'packages': 'Packages',
          'forgotPassword': 'Forgot Password ?',
          'biometric': 'Biometric',
          'privacyPolicy': 'Privacy Policy',
          'termsAndConditions': 'Terms & Conditions',
          'logout': 'Logout',
          'labInvestions': 'Lab Investigations',
          'selectTest': 'Select Test',
          'description': 'Description',
          'address': 'Address',
          'paymentMethod': 'Payment Method',
          'prescribedBy': 'Prescribed By',
          'self': 'Self',
          'doctor': 'Doctor',
          'outdoorDoctor': 'Outdoor Doctor',
          'select Doctor': 'Select Doctor',
          'summary': 'Summary',
          'datehour': 'Date & Hour',
          'package': 'Package',
          'test': 'Test',
          'price': 'Price',
          'grandTotal': 'Grand Total',
          'appointmentConfirm': 'Appointment Confirm',
          'attachPrescription': 'Attach Prescription',
          'login': 'LOGIN',
          'Login': 'Login',
          'donthaveanAccount': 'Don\'t have an account? ',
          'register': 'Register',
          'registerNow': 'Register Now',
          'fullName': 'Full Name',
          'yourMobNumber': 'Your Mobile Number',
          'email': 'Email',
          'dateOfBirth': 'Date of Birth',
          'gender': 'Gender',
          'password': 'Password',
          'retypePassword': ' Re-type Password',
          'changePassword': 'Change Password',
          'country': 'Country',
          'state': 'State',
          'city': 'City',
          'street': 'Street',
          'alreadyHaveAnAccount': 'Already have an account? ',
          'signin': 'Sign in',
          'registered': 'Registered',
          'registrationCompleted':
              'Registration has been Successfully \n Completed',
          'ok': 'OK',
          'payfromYourWallet': 'Pay from your Wallet',
          'payOnline': 'Pay Online',
          'payAtClinic': 'Pay At Clinic',
          'congratulations': 'Congratulations',
          'myAppointments': 'My Appointments',
          'bookyourAppointments': 'Book your Appointment',
          'searchDoctor': 'Search Doctor',
          'patients': "Patients",
          'yearExperience': 'Years of Experience',
          'rating': 'Ratings',
          'reviews': 'Reviews',
          'descriptions': 'Descriptions',
          'workingTime': 'Working Time',
          'online&Clinic': 'Online & Home Consultation Charges',
          'bookAppointment': 'Book Appointment',
          'welcomeTo': 'Welcome to',
          'username': 'Username',
          'oopsFailed': 'Oops, Failed',
          'appointmentFailed': 'Appointment Failed',
          'checkInternet':
              'Please Check your Internet Connection And Try again',
          'appointmentBooked': 'Appointment Booked Successfully',
          'viewAppointment': 'View Appointment',
          'cancel': 'Cancel',
          'glucose': "Glucose",
          'bloodPressure': 'Blood Pressure values',
          'measurements': 'Measurements',
          'connect': 'Connect',
          'pulse': 'Pulse',
          'temperature': 'Temperature',
          'labTestResult': 'Lab Test Result',
          'status': 'Status',
          'pending': 'Pending',
          'allergies': 'Allergies',
          'addGlucose': 'Add Glucose',
          'normal': 'Normal',
          'fasting': 'Fasting',
          'values': 'Values',
          'condition': 'Condition',
          'saveRecord': 'Save Record',
          'calculate': 'Calculate',
          'bmiCalculator': 'BMI Calculator',
          'BMI': 'BMI',
          'glucoseLevelMonitor': 'Glucose Level Monitor',
          'enterValue': 'Enter Value',
          'goodAfternoon': 'Good Afternoon',
          'collectLocationData':
              'Tabib AlBait Patient Care collects Location data to enable Home Sampling Services even when is closed or not in use',
          'permissions': 'Permissions',
          'deleteAccount': 'Delete Account',
          'languages': 'Languages',
          'identityNumber': 'Identity Number',
          'signup': 'Sign up ?',
          'bpm': 'BPM',
          'date': 'Date',
          'time': 'Time',
          'searchForSpecialities': 'Search For Specialists',
          'consultNow': 'Consult Now',
          'specialists': 'Specialists',
          'upcomingAppointments': 'Upcoming Appointments',
          'dateAndTime': 'Date and Time',
          'reschedule': 'Reschedule',
          'onlineConsultation': 'Online Consultation',
          'information1':
              'Our system and apps are mainly targeting Health Care and medical. We are collecting some other information and permissions in our apps to improve user experience and app functionality. The information we collect is ephemerally processed i.e. it is only used to start some service or functionality involved inside the application and not used after it is stopped. Some important one are mentioned below with prominent disclosure/reasons for collection',
          'information2':
              'Location: In order to show nearby doctors, app needs to get this permission from user. By enabling Location-Based services on your device, you agree and acknowledge  that (a) device data that is collected from you is directly relevant to your use of the App, (b) We may provide Location-Based services related to and based on your then-current location, and (c) We may use any information collected in connection with its provision of the App.For video calling between doctor and patient.For audio calling  between doctor and patient (a)User/Patient can upload profile picture (b) User/Patient can upload health records and files for doctor to examine (c)User/Patient can download and view reports etc.',
          'usage':
              'We use the informative we collect in various ways, including to: (a)Provide, operate, and maintain our services and products (b)Understand and analyze how you use our services and products (c)Develop new product, services features, and functionality (d) Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes (e) Send your emails (f) Find and prevent fraud.',
          'disclosure':
              'We may disclose personal information to any person performing audit, legal, operational or other services for us. We will use information which does not identify the individual for these activities whenever reasonably possible. Under the CCPA, among other rights, California consumers have the  right to Request that a business that collects personal data disclose the categories and specific pieces of personal data that a business has collected about consumers, Request that a business delete any personal data, not sell the consumers personal data. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us via customer supportUnder the GDPR Data Protection Rights, every user is entitled to the right to request copies of your personal data. We may charge you a small fell for the service, right to request that we correct any information you believe in inaccurate, right to request that we erase your personal data, restrict its processing, object to our processing of your personal, transfer the data that we have collected to another organization or directly to you data under certain conditions. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us via customer support',
          'consent':
              'By using our website, services & products, you hereby consent to our Privacy Policy and agree to its terms. If you are a doctor or medical professional registering on this App, by enrolling in or using this service, you hereby confirm that usage is at your own risk and you release and agree to hold harmless the providers, developers, deployers from liability for adverse consequences, including but limited to claims, actions or legal proceedings by third parties, loss or breach of any private data and/or damages suffered as a result thereof.',
          'consentTitle': 'Consent',
          'usageTitle': 'Usage',
          'disclosureTitle': 'Disclosure',
          'informationWeCollect': 'Information we Collect',
          'iHaveRead': 'I have read and understand',
          'theTermsAndCondition': ' the Terms and Conditions',
          'accept': 'Accept',
          'decline': 'Decline',
          'height': 'Height',
          'weight': 'Weight',
          'add': 'Add',
          'servicesHome': 'Services (Home)',
          'teleConsultation': 'Tele Consultation',
          'diagnostics': 'Diagnostics',
          'physio': 'Physio',
          'nursing': 'Nursing',
          'caregiver': 'Caregiver',
          'respiratoryTherapy': 'Respiratory Therapy',
          'dietitian': 'Dietitian',
          'serviceSelected': 'Service Selected',
          'collectesData':
              'collects Location data to enable  Services Home even when is closed or not in use',
          'agree': 'Agree',
          'appointmentNotes': 'Appointment Notes',
          'deny': 'Deny',
          'search': 'Search',
          'homeVisit': 'Home Visit',
          'online': 'Online',
          'subTotal': 'Sub Total',
          'minFee': 'Min. Fee',
          'doctorSchedule': 'Doctor Schedule',
          'fee': 'Fee',
          'charges': 'Charges',
          'selectAddress': 'Select Address',
          'selectLocation': 'Select Location',
          'goodMorning': 'Good Morning',
          'token': 'Token',
          'ecg': 'ECG',
          'selectLanguage': 'Select Language',
          'english': 'English',
          'arabic': 'Arabic',
          'hour': 'Hour',
          'homeService': 'Home Service',
          'labInvestigationBooking': 'Lab Investigation Booking',
          'experience': 'Experience',
          'paying': 'Paying',
          'serviceBooked': 'Service Booked Successfully.',
          'appointmentSuccessful':
              "Appointment Successfully Booked. You Will receive a notification",
          'failedAppointment':
              'Appointment failed please check your internet connection then try again.',
          'favorites': 'Favorites',
          'noFavorites': 'No Favorite Doctors Added',
          'contact': 'Contact No.',
          'c': 'Province/State',
          'editProfile': 'Edit Profile',
          'update': 'Update',
          'healthanalysis': 'Health Analysis',
          'herearesomehealth': 'Here are some Health facts about ',
          'men': 'Men',
          'In': 'in',
          'dubai': 'Dubai, UAE ',
          'doctorName': 'Doctor Name',
          'careGivers': 'Caregiver',
          'disclaimer': 'Disclaimer',
          'services': 'Services',
          'go': 'Go',
          'patienthistory': 'Patient History',
          'iamonline': 'I am Online',
          'iamoffline': 'I am Offline',
          'regno': 'REG NO. ',
          'consultingqueue': 'Consulting Queue',
          'configureappointments': 'Configure \n Appointments',
          'adjustyourschedule': 'Adjust your Schedule',
          'manageappointments': 'Manage \n Appointments',
          'approve/aisapproveappointments':
              'Approve/Disapprove \n Appointments',
          'consultedvault': 'Consulted \n Vault',
          'viewconsultations': 'View Consultations',
          'healthsummary': 'Health \n Summary',
          'patientmonitoring': 'Patient Monitoring',
          'assessmentform': 'Assessment Form',
          'pleaseenteryourname': 'Please enter your name',
          'pleaseenteryourmobilenumber': 'Please enter your mobile number',
          'mobilenumber': 'Mobile Number',
          'pleaseenteryouremail': 'Please enter your email',
          'pleaseselectyourcountry': 'Please select your Country',
          'pleaseselectyourprovince': 'Please select your Province',
          'pleaseselectyourcity': 'Please select your City',
          'province': 'Province',
          'pleaseselectyouraddress': 'Please select your Address',
          'successfullyupdate': 'Successfully Update',
          'failedtoupdate': 'Failed to update',
          'personal': 'Personal',
          'security': 'Security',
          'title': 'Title',
          'enteryourfirstname': 'Enter your First Name',
          'firstname': 'First Name',
          'enteryourlastname': 'Enter your Last Name',
          'lastname': 'Last Name',
          'maritalstatus': 'Marital Status',
          'prescribedby': 'Prescribed By',
          'nationalid': 'National ID',
          'passport': 'Passport',
          'enteryouridnumber': 'Enter your ID Number',
          'idnumber': 'ID Number',
          'enteryourimcno': 'Enter your IMC No',
          'imcno': 'IMC No.',
          'addpmccertificate': 'Add PMC Certificate',
          'speciality': 'Speciality',
          'subspeciality': 'Sub Speciality',
          'dateofbirth': 'Date of Birth',
          'age': 'Age',
          'enteryouremail': 'Enter your Email',
          'saveandproceed': 'Save and Proceed',
          'addpicture': 'Add Picture',
          'selecttitle': 'Select Title',
          'selectgender': 'Select Gender',
          'enteryourfullname': 'Enter your Full Name',
          'enteryourpassword': 'Enter your Password',
          'enteryourconfirmationpassword': 'Enter your Confirm Password',
          'confirmationpassword': 'Confirm Password',
          'pleasesavepersonaldetails': 'Please Save Personal Details',
          'forgottenpassword': 'Forgotten Password',
          'ithappenkindlyenterthemobilenumberassociatedwithyouraccount':
              'It happen, kindly enter the Number \n associated with your account',
          'verifycode': 'Verify Code',
          'enteryourmobilenumber': 'Enter your Mobile Number',
          'entercode': 'Enter Code',
          'kindlyenterthecodesenttoyournumber':
              'Kindly enter the code sent to your number',
          'enternumber': 'Enter Number',
          'expirein': 'Expires in',
          'codeexpire': 'Code Expire',
          'expire': 'Expire',
          'createnewpassword': 'Create New Password',
          'kindlyenterauniquepassword': 'Kindly enter a unique password',
          'changepassword': 'Change Password',
          'oldpassword': 'Old Password',
          'enteryouroldpassword': 'Enter your Old Password',
          'newpasswordsshouldmatch': 'New Passwords Should Match',
          'worngemail': 'Worng Email',
          'wrongcode': 'Wrong Verification Code',
          'view': 'View',
          'all': 'All',
          'upcoming': 'Upcoming',
          'configureappointmentappbar': 'Configure Appointments',
          'setyouravailabilitytostartattendingpatients':
              'Set your availability to start \n attending patients',
          'hospitalclinic': 'Hospital/Clinic',
          'onlinevideoconsultation': 'Online Video Consultation',
          'selectdays': 'Select Days',
          'addhoursofyouravailability': 'Add hours of your availability',
          'addmorehours': '+ Add more hours',
          'feetimeSlot': 'Fee & Time Slot',
          'consultancyfee': 'Consultancy Fee',
          'aed': 'AED',
          'followupfee': 'Follow Up Fee',
          'slotduration': 'Slot Duration (HH:MM)',
          'followupdays': 'Follow Up Days',
          'nonpaidappointmentapproval': ' Non-Paid Appointment Approval \n',
          'approvalcriteria': ' Approval Criteria',
          'monday': 'Monday',
          'tuesday': 'Tuesday',
          'wednesday': 'Wednesday',
          'thursday': 'Thursday',
          'friday': 'Friday',
          'saturday': 'Saturday',
          'sunday': 'Sunday',
          'recenttransections': 'Recent Transections',
          'receivedamount': 'Received Amount',
          'withdraw': 'Withdraw',
          'availablebalance': 'Available Balance',
          'addtopupcredit': 'Add Top up Credit',
          'chooseyourtopupamount': 'Choose your top up amount',
          'enterotheramount': 'Enter other amount',
          'otheramount': 'Other Amount',
          'addcard': '+Add Card',
          'paymentmethod': 'Payment Method',
          'card': 'Card',
          'entercardnumber': 'Enter Card Number',
          'expirydate': 'Expiry Date ( mm/yy )',
          'cvv': 'CVV',
          'cardholdername': 'Card holder name',
          'amount': 'Amount',
          'addamount': 'Add Amount',
          'toverifyyourcredit/debitcard,asmallamountwillbechargedfromyou,afterverificationamountwillbeaddedtoyourwallet':
              'To verify your credit/debit card, a small amount will be charged from you, after verification amount will be added to your wallet',
          'topupyourwallet': 'Top Up Your Wallet',
          'appointmentshistory': 'Appointments History',
          'to': 'To',
          'mrno': 'Mr no : ',
          'visitno': 'Visit no. ',
          'address|': 'Address | ',
          'erx': 'eRX',
          'selectbranch': 'Select Branch',
          'selecthospitalclinic': 'Select Hospital/Clinic',
          'healthsummaryappbar': 'Health Summary',
          'Mrno': 'Mr, No. ',
          'Mrnospace': '  Mr, No. ',
          'deviceconnected': 'Device Connected',
          'devicedisconnect': 'Device Disconnect',
          'random': 'Random',
          'bloodpressure': 'Blood Pressure',
          'attendsession': 'Attend Session',
          'prescribemedicinetests': 'Prescribe Medicine / Tests',
          'complains': 'Complains',
          'labinvestigation': 'Lab Investigation',
          'medicine': 'Medicine',
          'type': ' Type',
          'qty': 'Qty',
          'frequency': ' Frequency',
          'duration': 'Duration',
          'freq': 'Freq',
          'dur': 'Dur',
          'finding': 'Finding',
          'notes': 'Notes',
          'writenotes': 'Write Notes',
          'prescribe': 'Prescribe',
          'yoursessionwith': 'Your session with ',
          'iscomplete': 'is complete! 🎉',
          'completed': 'Completed',
          'wewouldlovetohearfromyou': 'We would love to hear from you',
          'writeyourfeedbackhere': 'Write your feedback here',
          'feedback': 'Feedback',
          'pleaseenterfeedback': 'Please Enter Feedback',
          'submit': 'Submit',
          'skipgotoconsultingqueue': 'Skip & Go to Consulting Queue',
          'thankyouforthefeedback': 'Thank you for the feedback!',
          'gotoconsultingqueue': 'Go to Consulting Queue',
        },
        "ar_SA": {
          'prescribemedicinetests': 'وصف الدواء / الاختبارات',
          'complains': 'يشكو',
          'labinvestigation': 'التحقيق المختبري',
          'medicine': 'الدواء',
          'type': 'يكتب',
          'qty': 'الكمية',
          'frequency': ' تكرار',
          'duration': 'مدة',
          'freq': 'التكرار',
          'dur': 'دور',
          'finding': 'العثور على',
          'notes': 'ملحوظات',
          'writenotes': 'اكتب الملاحظات',
          'prescribe': 'وصفة',
          'yoursessionwith': 'جلستك مع',
          'iscomplete': 'اكتمل! 🎉',
          'completed': 'مكتمل',
          'wewouldlovetohearfromyou': 'كنا نحب أن نسمع منك',
          'writeyourfeedbackhere': 'اكتب ملاحظاتك هنا',
          'feedback': 'تعليق',
          'pleaseenterfeedback': 'الرجاء إدخال ردود الفعل',
          'submit': 'يُقدِّم',
          'skipgotoconsultingqueue': 'تخطي وانتقل إلى قائمة انتظار الاستشارة',
          'thankyouforthefeedback': 'شكرا لك على ملاحظاتك!',
          'gotoconsultingqueue': 'انتقل إلى قائمة انتظار الاستشارة',
          'attendsession': 'حضور الجلسة',
          'healthsummaryappbar': 'ملخص الصحة',
          'Mrno': 'السيد، لا. ',
          'Mrnospace': ' السيد، لا. ',
          'deviceconnected': 'الجهاز متصل',
          'devicedisconnect': 'قطع اتصال الجهاز',
          'random': 'عشوائي',
          'bloodpressure': 'ضغط الدم',
          'appointmentshistory': 'تاريخ المواعيد',
          'to': 'ل',
          'mrno': 'السيد لا : ',
          'visitno': 'رقم زيارة. ',
          'address|': 'العنوان | ',
          'erx': 'eRX',
          'selectbranch': 'حدد الفرع',
          'selecthospitalclinic': 'اختر المستشفى/العيادة',
          'topupyourwallet': 'قم بتعبئة محفظتك',
          'recenttransections': 'التحويلات الأخيرة',
          'receivedamount': 'المبلغ الذي تسلمه',
          'withdraw': 'ينسحب',
          'availablebalance': 'الرصيد المتوفر',
          'addtopupcredit': 'إضافة رصيد أعلى',
          'chooseyourtopupamount': 'اختر مبلغ التعبئة الخاص بك',
          'enterotheramount': 'أدخل المبلغ الآخر',
          'otheramount': 'كمية اخرى',
          'addcard': '+إضافة بطاقة',
          'paymentmethod': 'طريقة الدفع او السداد',
          'card': 'بطاقة',
          'entercardnumber': 'أدخل رقم البطاقة',
          'expirydate': 'تاريخ انتهاء الصلاحية ( مم / سنة )',
          'cvv': 'CVV',
          'cardholdername': 'إسم صاحب البطاقة',
          'amount': 'كمية',
          'addamount': 'أضف المبلغ',
          'toverifyyourcredit/debitcard,asmallamountwillbechargedfromyou,afterverificationamountwillbeaddedtoyourwallet':
              'للتحقق من بطاقة الائتمان/الخصم الخاصة بك، سيتم خصم مبلغ صغير منك، بعد إضافة مبلغ التحقق إلى محفظتك',
          'monday': 'الاثنين',
          'tuesday': 'يوم الثلاثاء',
          'wednesday': 'الأربعاء',
          'thursday': 'يوم الخميس',
          'friday': 'جمعة',
          'saturday': 'السبت',
          'sunday': 'الأحد',
          'approvalcriteria': 'معايير الموافقة',
          'nonpaidappointmentapproval': 'الموافقة على موعد غير مدفوع الأجر \n',
          'followupdays': 'أيام المتابعة',
          'slotduration': 'مدة الفتحة (س:د د)',
          'followupfee': 'رسوم المتابعة',
          'aed': 'درهم',
          'consultancyfee': 'رسوم الاستشارة',
          'feetimeSlot': 'الرسوم والوقت',
          'addmorehours': '+ إضافة المزيد من الساعات',
          'addhoursofyouravailability': 'أضف ساعات التوفر لديك',
          'selectdays': 'حدد الأيام',
          'onlinevideoconsultation': 'استشارة الفيديو عبر الإنترنت',
          'hospitalclinic': 'مستشفى/عيادة',
          'setyouravailabilitytostartattendingpatients':
              'قم بتعيين مدى توفرك للبدء \n في حضور المرضى',
          'configureappointmentappbar': 'تكوين المواعيد',
          'upcoming': 'القادمة',
          'all': 'الجميع',
          'consultingqueue': 'قائمة انتظار الاستشارة',
          'view': 'منظر',
          'wrongcode': 'رمز التحقق خاطئ',
          'worngemail': 'بريد إلكتروني خاطئ',
          'newpasswordsshouldmatch': 'يجب أن تتطابق كلمات المرور الجديدة',
          'changepassword': 'تغيير كلمة المرور',
          'createnewpassword': 'إنشاء كلمة مرور جديدة',
          'kindlyenterauniquepassword': 'يرجى إدخال كلمة مرور فريدة',
          'codeexpire': 'انتهاء صلاحية الرمز',
          'expire': 'تنقضي',
          'expirein': 'ينتهي في',
          'enternumber': 'أدخل رقم',
          'entercode': 'ادخل الرمز',
          'kindlyenterthecodesenttoyournumber':
              'يرجى إدخال الرمز المرسل إلى رقمك',
          'enteryourmobilenumber': 'أدخل رقم هاتفك المحمول',
          'forgottenpassword': 'كلمة سر منسية',
          'ithappenkindlyenterthemobilenumberassociatedwithyouraccount':
              'في حالة حدوث ذلك، يرجى إدخال الرقم المرتبط بحسابك',
          'verifycode': 'التحقق من كود',
          'enteryourfullname': 'أدخل اسمك الكامل',
          'enteryourpassword': 'ادخل رقمك السري',
          'enteryourconfirmationpassword': 'أدخل تأكيد كلمة المرور الخاصة بك',
          'confirmationpassword': 'تأكيد كلمة المرور',
          'pleasesavepersonaldetails': 'الرجاء حفظ التفاصيل الشخصية',
          'enteryourfirstname': 'أدخل اسمك الأول',
          'firstname': 'الاسم الأول',
          'enteryourlastname': 'أدخل اسمك الأخير',
          'lastname': 'اسم العائلة',
          'maritalstatus': 'الحالة الاجتماعية',
          'prescribedby': 'المنصوص عليها',
          'nationalid': 'الهوية الوطنية',
          'passport': 'جواز سفر',
          'enteryouridnumber': 'أدخل رقم الهوية الخاص بك',
          'idnumber': 'رقم الهوية',
          'enteryourimcno': 'أدخل رقم IMC الخاص بك',
          'imcno': 'رقم آي إم سي',
          'addpmccertificate': 'إضافة شهادة PMC',
          'speciality': 'تخصص',
          'subspeciality': 'التخصص الفرعي',
          'dateofbirth': 'تاريخ الميلاد',
          'age': 'عمر',
          'enteryouremail': 'أدخل بريدك الإلكتروني',
          'saveandproceed': 'إحفظ وتابع',
          'addpicture': 'إضافة الصورة',
          'selecttitle': 'حدد العنوان',
          'selectgender': 'حدد نوع الجنس',
          'title': 'عنوان',
          'security': 'حماية',
          'personal': 'شخصي',
          'failedtoupdate': 'اخفاق التحديث',
          'successfullyupdate': 'تم التحديث بنجاح',
          'pleaseselectyouraddress': 'الرجاء تحديد عنوانك',
          'province': 'مقاطعة',
          'pleaseselectyourprovince': 'الرجاء تحديد المقاطعة الخاصة بك',
          'pleaseselectyourcity': 'الرجاء تحديد مدينتك',
          'pleaseselectyourcountry': 'الرجاء تحديد بلدك',
          'pleaseenteryouremail': 'رجاءا أدخل بريدك الإلكتروني',
          'mobilenumber': 'رقم الهاتف المحمول',
          'pleaseenteryourmobilenumber': 'الرجاء إدخال رقم هاتفك المحمول',
          'pleaseenteryourname': 'من فضلك أدخل إسمك',
          'assessmentform': 'استمارة التقييم',
          'patientmonitoring': 'مراقبة المريض',
          'healthsummary': 'الصحة \n ملخص',
          'viewconsultations': 'عرض المشاورات',
          'consultedvault': 'تمت استشارة \n قبو',
          'approve/aisapproveappointments': 'الموافقة/الرفض \n المواعيد',
          'manageappointments': 'إدارة \n المواعيد',
          'adjustyourschedule': 'ضبط الجدول الزمني الخاص بك',
          "welcometo": "مرحبا بك في",
          "takecareofyourhealth": "اعتني بصحتك",
          "with": "مع",
          'goodmorning': "صباح الخير",
          'goodEvening': 'مساء الخير',
          'goodNight': 'Good Night',
          'goodAfterNoon': 'Good Afternoon',
          'onlineOffline': 'متصل غير متصل',
          'consultations': 'استشارات',
          'booknow': 'احجز الآن',
          'selectservices': 'حدد الخدمات',
          'homeSample': 'عينة المنزل',
          'imageBooking': 'حجز الصور',
          'doctorConsultation': 'استشارة الطبيب',
          'reports': 'التقارير',
          'healthSummary': 'ملخص الصحة',
          'healthAnalysis': 'التحليل الصحي',
          'todayAvailable': 'متوفر اليوم',
          'generalConsultation': 'الاستشارة العامة',
          'getAppointment': 'احصل على موعد',
          'home': 'بيت',
          'profile': 'حساب تعريفي',
          'schedule': 'جدول',
          'help': 'يساعد',
          'history': 'تاريخ',
          'familyMembers': 'أفراد الأسرة',
          'location': 'موقع',
          'wallet': 'محفظة',
          'packages': 'الحزم',
          'forgotPassword': 'هل نسيت كلمة السر ؟',
          'biometric': 'بصمات',
          'privacyPolicy': 'سياسة الخصوصية',
          'termsAndConditions': 'البنود و الظروف',
          'logout': 'تسجيل خروج',
          'labInvestions': 'التحقيقات المخبرية',
          'selectTest': 'حدد اختبار',
          'description': 'وصف',
          'address': 'عنوان',
          'paymentMethod': 'طريقة الدفع او السداد',
          'prescribedBy': 'المنصوص عليها',
          'self': 'الذات',
          'doctor': 'طبيب',
          'outdoorDoctor': 'طبيب خارجي',
          'select Doctor': 'اختر الطبيب',
          'summary': 'ملخص',
          'datehour': 'التاريخ والساعة',
          'package': 'طَرد',
          'test': 'امتحان',
          'price': 'سعر',
          'grandTotal': 'المجموع الإجمالي',
          'appointmentConfirm': 'تأكيد الموعد',
          'attachPrescription': 'إرفاق وصفة طبية',
          'login': 'تسجيل الدخول',
          'Login': 'تسجيل الدخول',
          'donthaveanAccount': ' ليس لديك حساب؟',
          'register': 'يسجل',
          'registerNow': 'سجل الان',
          'fullName': 'الاسم الكامل',
          'yourMobNumber': 'رقم هاتفك',
          'email': 'بريد إلكتروني',
          'dateOfBirth': 'تاريخ الميلاد',
          'gender': 'جنس',
          'password': 'كلمة المرور',
          'retypePassword': 'أعد إدخال كلمة السر',
          'country': 'دولة',
          'state': 'ولاية',
          'city': 'مدينة',
          'street': 'شارع',
          'alreadyHaveAnAccount': ' هل لديك حساب؟',
          'signin': 'تسجيل الدخول',
          'registered': 'مسجل',
          'registrationCompleted': 'تم التسجيل بنجاح اكتمل',
          'ok': 'نعم',
          'payfromYourWallet': 'ادفع من محفظتك',
          'payOnline': 'ادفع عبر الإنترنت',
          'payAtClinic': 'الدفع في العيادة',
          'congratulations': 'تهانينا',
          'myAppointments': 'مواعيدي',
          'bookyourAppointments': 'احجز موعدك',
          'searchDoctor': 'البحث عن الأطباء',
          'patients': "مرضى",
          'yearExperience': 'سنوات من الخبرة',
          'rating': 'التقييمات',
          'reviews': 'التعليقات',
          'descriptions': 'الأوصاف',
          'workingTime': 'وقت العمل',
          'online&Clinic': 'رسوم الاستشارة عبر الإنترنت والعيادة',
          'bookAppointment': 'موعد الكتاب',
          'welcomeTo': 'مرحبا بك في',
          'username': 'اسم المستخدم',
          'oopsFailed': 'عفوًا، فشل',
          'appointmentFailed': 'فشل الموعد',
          'checkInternet': 'الرجاء التحقق من اتصالك بالإنترنت وحاول مرة أخرى',
          'appointmentBooked': 'تم حجز الموعد بنجاح',
          'viewAppointment': 'عرض الموعد',
          'cancel': 'يلغي',
          'glucose': "الجلوكوز",
          'bloodPressure': 'ضغط الدم',
          'measurements': 'قياسات',
          'connect': 'يتصل',
          'pulse': 'نبض',
          'temperature': 'درجة حرارة',
          'labTestResult': 'نتيجة الاختبار المعملي',
          'status': 'حالة',
          'pending': 'قيد الانتظار',
          'allergies': 'الحساسية',
          'addGlucose': 'أضف الجلوكوز',
          'normal': 'طبيعي',
          'fasting': 'صيام',
          'values': 'قيم',
          'condtition': 'حالة',
          'saveRecord': 'حفظ السجل',
          'calculate': 'احسب',
          'bmiCalculator': 'حاسبة مؤشر كتلة الجسم',
          'BMI': 'مؤشر كتلة الجسم',
          'glucoseLevelMonitor': 'مراقب مستوى الجلوكوز',
          'enterValue': 'أدخل القيمة',
          'goodAfternoon': 'مساء الخير',
          'collectLocationData':
              'يقوم طبيب البيت لرعاية المرضى بجمع بيانات الموقع لتمكين خدمات أخذ العينات المنزلية حتى عندما تكون مغلقة أو غير مستخدمة',
          'permissions': 'الأذونات',
          'deleteAccount': 'حذف الحساب',
          'languages': "لغة",
          'identityNumber': 'رقم الهوية',
          'signup': 'اشتراك',
          'bpm': 'نبضة في الدقيقة',
          'date': 'تاريخ',
          'time': 'وقت',
          'searchForSpecialities': 'البحث عن القسم',
          'consultNow': 'استشر الآن',
          'specialists': 'المتخصصين',
          'upcomingAppointments': 'المواعيد القادمة',
          'dateAndTime': 'التاريخ و الوقت',
          'reschedule': 'إعادة جدولة',
          'onlineConsultation': 'التشاور عبر الإنترنت',
          'information1':
              'يستهدف نظامنا وتطبيقاتنا بشكل أساسي الرعاية الصحية والطبية. نقوم بجمع بعض المعلومات والأذونات الأخرى في تطبيقاتنا لتحسين تجربة المستخدم ووظائف التطبيق. تتم معالجة المعلومات التي نجمعها بشكل مؤقت، أي أنها تستخدم فقط لبدء بعض الخدمات أو الوظائف الموجودة داخل التطبيق ولا يتم استخدامها بعد إيقافها. تم ذكر بعض الأمور المهمة أدناه مع الإفصاح/أسباب التجميع البارزة',
          'information2':
              'الموقع: لإظهار الأطباء القريبين، يحتاج التطبيق إلى الحصول على هذا الإذن من المستخدم. من خلال تمكين الخدمات المستندة إلى الموقع على جهازك، فإنك توافق وتقر بأن (أ) بيانات الجهاز التي يتم جمعها منك ذات صلة مباشرة باستخدامك للتطبيق، (ب) قد نقدم خدمات تعتمد على الموقع تتعلق وتستند إلى موقعك الحالي في ذلك الوقت، و (ج) يجوز لنا استخدام أي معلومات تم جمعها فيما يتعلق بتوفير التطبيق. لإجراء مكالمات فيديو بين الطبيب والمريض. لإجراء مكالمات صوتية بين الطبيب والمريض (أ) يمكن للمستخدم/المريض تحميل صورة الملف الشخصي (ب) يمكن للمستخدم/المريض تحميل السجلات والملفات الصحية ليقوم الطبيب بفحصها (ج) يمكن للمستخدم/المريض تنزيل وعرض التقارير وما إلى ذلك.',
          'usage':
              'نحن نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك: (أ) توفير خدماتنا ومنتجاتنا وتشغيلها وصيانتها (ب) فهم وتحليل كيفية استخدامك لخدماتنا ومنتجاتنا (ج) تطوير منتج جديد وميزات الخدمات و الوظيفة (د) التواصل معك، إما بشكل مباشر أو من خلال أحد شركائنا، بما في ذلك خدمة العملاء، لتزويدك بالتحديثات والمعلومات الأخرى المتعلقة بالموقع، ولأغراض تسويقية وترويجية (هـ) إرسال رسائل البريد الإلكتروني الخاصة بك (و) البحث عن الاحتيال ومنعه',
          'disclosure':
              'يجوز لنا الكشف عن المعلومات الشخصية لأي شخص يقوم بتقديم خدمات التدقيق أو الخدمات القانونية أو التشغيلية أو غيرها من الخدمات لنا. سوف نستخدم المعلومات التي لا تحدد هوية الفرد لهذه الأنشطة كلما كان ذلك ممكنًا بشكل معقول. بموجب قانون CCPA، من بين حقوق أخرى، يحق للمستهلكين في كاليفورنيا أن يطلبوا من الشركة التي تجمع البيانات الشخصية الكشف عن فئات وأجزاء محددة من البيانات الشخصية التي جمعتها الشركة عن المستهلكين، ومطالبة الشركة بحذف أي بيانات شخصية، وعدم بيعها. البيانات الشخصية للمستهلكين. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، فيرجى الاتصال بنا عبر دعم العملاء بموجب حقوق حماية البيانات الخاصة باللائحة العامة لحماية البيانات (GDPR)، يحق لكل مستخدم طلب نسخ من بياناتك الشخصية. قد نفرض عليك رسومًا صغيرة مقابل الخدمة، والحق في طلب تصحيح أي معلومات تعتقد أنها غير دقيقة، والحق في طلب مسح بياناتك الشخصية، وتقييد معالجتها، والاعتراض على معالجتنا لبياناتك الشخصية، ونقل البيانات التي لقد قمنا بجمع البيانات إلى منظمة أخرى أو إليك مباشرة في ظل ظروف معينة. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، يرجى الاتصال بنا عبر دعم العملاء',
          'consent':
              'باستخدام موقعنا وخدماتنا ومنتجاتنا، فإنك توافق بموجبه على سياسة الخصوصية الخاصة بنا وتوافق على شروطها. إذا كنت طبيبًا أو متخصصًا طبيًا تقوم بالتسجيل في هذا التطبيق، فمن خلال التسجيل في هذه الخدمة أو استخدامها، فإنك تؤكد بموجب هذا أن الاستخدام يقع على مسؤوليتك الخاصة، كما أنك تحرر وتوافق على إعفاء مقدمي الخدمة والمطورين والناشرين من المسؤولية عن العواقب الضارة. ، بما في ذلك على سبيل المثال لا الحصر المطالبات أو الإجراءات أو الإجراءات القانونية من قبل أطراف ثالثة أو فقدان أو خرق أي بيانات خاصة و/أو الأضرار التي لحقت نتيجة لذلك',
          'consentTitle': 'موافقة',
          'usageTitle': 'الاستخدام',
          'disclosureTitle': 'إفشاء',
          'informationWeCollect': 'المعلومات التي نجمعها',
          'iHaveRead': 'لقد قرأت وفهمت',
          'theTermsAndCondition': 'الشروط والأحكام',
          'accept': 'يقبل',
          'decline': 'انخفاض',
          'height': 'ارتفاع',
          'weight': 'وزن',
          'add': 'يضيف',
          'servicesHome': 'الخدمات (المنزلية)',
          'teleConsultation': 'الاستشارة عن بعد',
          'diagnostics': 'التشخيص',
          'physio': 'فيزيائي',
          'nursing': 'التمريض',
          'caregiver': 'الراعي',
          'respiratoryTherapy': 'العلاج التنفسي',
          'dietitian': 'اخصائي تغذيه',
          'serviceSelected': 'الخدمة مختارة',
          'agree': 'يوافق',
          'appointmentNotes': 'ملاحظات التعيين',
          'deny': 'ينكر',
          'search': 'يبحث',
          'homeVisit': 'زيارة منزلية',
          'online': 'متصل',
          'subTotal': 'المجموع الفرعي',
          'minFee': 'الحد الأدنى للرسوم',
          'doctorSchedule': 'جدول الطبيب',
          'fee': 'مصاريف',
          'charges': 'رسوم',
          'selectAddress': 'حدد العنوان',
          'selectLocation': 'اختر موقعا',
          'goodMorning': 'صباح الخير',
          'token': 'رمز مميز',
          'ecg': 'تخطيط القلب الكهربي',
          'selectLanguage': 'اختار اللغة',
          'hour': 'ساعة',
          'homeService': 'خدمة منزلية',
          'labInvestigationBooking': 'حجز الفحوصات المخبرية',
          'experience': 'خبرة',
          'paying': 'الدفع',
          'serviceBooked': 'تم حجز الخدمة بنجاح',
          'appointmentSuccessful': "تم حجز الموعد بنجاح. سوف تتلقى إخطارا",
          'failedAppointment':
              'Appointment failed please check your internet connection then try again.',
          'favorites': 'المفضلة',
          'noFavorites': 'لم تتم إضافة أي الأطباء المفضلين',
          'contact': 'رقم الاتصال',
          'province/state': 'المقاطعة/الولاية',
          'editProfile': 'تعديل الملف الشخصي',
          'mobNumber': 'رقم الهاتف المحمول',
          'update': 'تحديث',
          'healthanalysis': 'تحليل الصحة',
          'herearesomehealth': 'فيما يلي بعض الحقائق الصحية حول',
          'men': 'رجال',
          'In': 'في',
          'dubai': 'دبي الامارات العربية المتحدة',
          'doctorName': 'اسم الطبيب',
          'careGiver': 'الراعي',
          'condition': 'حالة',
          'disclaimer': 'تنصل',
          'services': 'خدمات',
          "manageYourHealth": 'إدارة صحتك معنا',
          'go': 'يذهب',
          'changePassword': 'تغيير كلمة المرور',
          'patienthistory': 'تاريخ المريض',
          'iamonline': 'انا متصل بالنت',
          'iamoffline': 'أنا غير متصل',
          'regno': 'رقم التسجيل. ',
          'configureappointments': 'تكوين \n المواعيد'
        }
      };
}
